name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"] # Или master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm ci

      - name: Build
        run: pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: "./out" # Папка статического экспорта Next.js

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
